services:
  app:
    image: run-tracker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: run-tracker-api
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - run-tracker-network
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app

  postgres:
    image: postgres:17.6-alpine3.22
    container_name: run-tracker-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DB}", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - run-tracker-network

volumes:
  pgdata:
    name: run-tracker-pgdata

networks:
  run-tracker-network:
    driver: bridge
